language: python
python:
  - "3.11"  # Use a stable Python version
dist: focal
os: linux

env:
  - BASE_PATH="backend/nightwalkers" FRONTEND_PATH="frontend"

# Install dependencies
install:
  - pip install -r backend/nightwalkers/requirements.txt
  - pip install black flake8 coverage coveralls

# Install Node.js and frontend dependencies
  - nvm install 22  # Install Node.js 22 (or the version your Next.js app requires)
  - npm install -g npm@latest  # Update npm to the latest version
  - cd $FRONTEND_PATH && npm install --legacy-peer-deps && cd ..  # Install frontend dependencies

# Make the script executable
before_script:
  - chmod +x deploy-to-render.sh
  - chmod +x deploy-to-production.sh
  - chmod +x deploy-to-develop.sh
  - chmod +x deploy-to-netlify.sh

# Run checks and tests
script:
  - pwd

  - black --check backend/nightwalkers/
  - flake8 backend/nightwalkers/

  - coverage run --source=$BASE_PATH $BASE_PATH/manage.py test $BASE_PATH
  - coverage report  # Print coverage report
  - coverage xml  # Generate coverage XML for coveralls

  # Frontend build
  - cd $FRONTEND_PATH && npm run build && cd ..  # Build the Next.js app

# Report coverage to coveralls
after_success:
  - coveralls --service=travis-pro

# Deploy to AWS Elastic Beanstalk upon successful tests
deploy:
  provider: script
  script: ./deploy.sh  # Custom script to deploy to Render
  cleanup: false
  on:
    branches: 
      - main  # Update to your main branch name (e.g., main, master)
      - develop  # Update to your develop branch name
# Notifications (optional)
notifications:
  email:
    on_success: never
    on_failure: always