language: python
python:
  - "3.11"  # Use a stable Python version
dist: focal
os: linux

# Install dependencies
install:
  - pip install -r backend/requirements.txt  # Path to requirements.txt inside the backend folder
  - pip install black flake8 coverage coveralls

# Run checks and tests
script:
  - black --check backend/  # Validate code formatting with black (point to backend folder)
  - flake8 backend/  # Check code style with flake8 (point to backend folder)
  - coverage run --source=backend/mysite manage.py test backend/mysite  # Run tests with coverage (update paths)
  - coverage report  # Print coverage report
  - coverage xml  # Generate coverage XML for coveralls

# Report coverage to coveralls
after_success:
  - coveralls --service=travis-pro

# Deploy to AWS Elastic Beanstalk upon successful tests
deploy:
  provider: script
  script: ./deploy-to-render.sh  # Custom script to deploy to Render
  cleanup: false
  on:
    branch: main  # Update to your main branch name (e.g., main, master)

# Notifications (optional)
notifications:
  email:
    on_success: never
    on_failure: always